/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 4-klambert
 */
public class Playerstatistics extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Playerstatistics.class.getName());
    /**
     * Creates new form Statistics
     */
    public Playerstatistics() {
        initComponents();
        ResultSet vPlayer;
        String url = "jdbc:mysql://185.156.138.148/4-klambert";
        String user = "4-klambert";
        String password = "Duty3-Palace-Area";
        String vQueryplayer = "SELECT players_name FROM Players";
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
            Connection connect = DriverManager.getConnection(url, user, password);
            PreparedStatement ps1 = connect.prepareStatement(vQueryplayer);
            vPlayer = ps1.executeQuery();
            while(vPlayer.next()) {
                Player.addItem(vPlayer.getString("players_name"));
            }
            } catch (Exception e) {
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Player = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BackButton2 = new javax.swing.JButton();
        StsubmitButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Player.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Player" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Statistics");

        jLabel2.setText("Choose your player");

        BackButton2.setText("Back");
        BackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton2ActionPerformed(evt);
            }
        });

        StsubmitButton.setText("Submit");
        StsubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StsubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(BackButton2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StsubmitButton)
                    .addComponent(Player, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Player, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StsubmitButton)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton2ActionPerformed
        homescreen hs = new homescreen();
        hs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButton2ActionPerformed

    private void StsubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StsubmitButtonActionPerformed
        // TODO add your handling code here:
        String sPlayer = String.valueOf(Player.getSelectedItem());
        java.sql.ResultSet vStats = null;
        Statement sta = null;
        String url2 = "jdbc:mysql://185.156.138.148/4-klambert";
        String user2 = "4-klambert";
        String password2 = "Duty3-Palace-Area";
        String vQuerystats = null;
        DefaultTableModel model = new DefaultTableModel();
        Vector columnNames = new Vector();
        Vector data = new Vector();  
        int x = 0;
        
        try {
            // create a connection to mysql db 
            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
            Connection connection2 = DriverManager.getConnection(url2, user2, password2);
            // build our sql statement to add a team from the team name box
            // String query = "INSERT INTO Teams (team_name) values('" + Teamname + "')";
            vQuerystats = "select s.match_id,m.dateplayed,p.players_name,s.runrate,s.catches,s.times_out,s.wickets_taken,t.team_name " +
                "from Stats s, Teams t, Players p, Matches m " +
                "where s.player_id = p.player_id " +
                "and s.team_id = t.team_id " +
                "and s.match_id = m.match_id " +
                "and p.players_name = \""+ sPlayer +"\";";
            sta = connection2.createStatement();
            // execute the query
            vStats = sta.executeQuery(vQuerystats);
            
            java.sql.ResultSetMetaData metaData = vStats.getMetaData();
            int columnCount = metaData.getColumnCount();
            String[] scratchNames = new String[columnCount];
            scratchNames[0] = "Match ID";
            scratchNames[1] = "Date Played";
            scratchNames[2] = "Player Name";
            scratchNames[3] = "Run Rate";
            scratchNames[4] = "Catches";
            scratchNames[5] = "Outs";
            scratchNames[6] = "Wickets taken";
            scratchNames[7] = "Team Name";
            for (int i = 0; i < columnCount; i++) 
                columnNames.addElement( scratchNames[i] );
            
            
            //model.setColumnIdentifiers(columnNames);
            
            //Object[] row = new Object[columnCount];
            while (vStats.next())
            {
                Vector row = new Vector(columnCount);
                for (int i = 1; i <= columnCount; i++)
                {
                    row.addElement(vStats.getObject(i));
                }
                data.addElement(row);
            }
                    
            JTable table = new JTable(data, columnNames);
            JScrollPane scrollPane = new JScrollPane( table );
            
            JFrame frame = new JFrame("Player Stats");
            frame.add(scrollPane);

            // Set the size and location of the frame
            frame.setSize(800, 400);
            frame.setLocationRelativeTo(null);

            // Make the frame visible
            frame.setVisible(true);
            
        
            if (columnCount > 0) {
                x = 0;
            }
            
            if (x == 0) {
                // if we get here it broke
                // great JOptionPane.showMessageDialog(NTSubmitDB, "This team already exists");
            } else {
                // it was successfully added to the teams table in the mysql db
                // let the user know
                //JOptionPane.showMessageDialog(NTSubmitDB,
                //            "Welcome, " + msg + "Team has been sucessfully created");
                    }
                    // close the connection to the db and commit
                    connection2.close();
                } catch (Exception exception) {
                    exception.printStackTrace();
                }
        
        
    }//GEN-LAST:event_StsubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) 
        {

        }
        //</editor-fold>

        /* Create and display the form */
  
            
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton2;
    private javax.swing.JComboBox<String> Player;
    private javax.swing.JButton StsubmitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
        }

