/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author katy
 */
public class previous extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(previous.class.getName());

    /**
     * Creates new form previous
     */
    public previous() {
        initComponents();
        /*ResultSet vMatches;
        String url = "jdbc:mysql://185.156.138.148/4-klambert";
        String user = "4-klambert";
        String password = "Duty3-Palace-Area";
        String vQuerymatches = "SELECT * FROM Matches";
        */
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        submitbtn = new javax.swing.JButton();
        backbtn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Previous matches");

        submitbtn.setText("see");
        submitbtn.addActionListener(this::submitbtnActionPerformed);

        backbtn4.setText("Back");
        backbtn4.addActionListener(this::backbtn4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addComponent(backbtn4)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(submitbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backbtn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitbtn)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        // String sTeam = String.valueOf(team.getSelectedItem());
        
        java.sql.ResultSet vMatches = null;
        Statement sta = null;
        String url = "jdbc:mysql://185.156.138.148/4-klambert";
        String user = "4-klambert";
        String password = "Duty3-Palace-Area";
        DefaultTableModel model = new DefaultTableModel();
        Vector columnNames = new Vector();
        Vector data = new Vector();  
        int x = 0;
        
        try {
            // create a connection to mysql db 
            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
            Connection connection = DriverManager.getConnection(url, user, password);
            // build our sql statement to add a team from the team name box
            // String query = "INSERT INTO Teams (team_name) values('" + Teamname + "')";
            String vQuerymatches = "select m.match_id,m.dateplayed,t.team_name,a.team_name,m.home_score,m.away_score,w.team_name, " +
            "case when m.match_abandoned = 0 then 'No' else 'Yes' end as \"Match Abandoned\" " +
            "from Matches m, Teams t, Teams a, Teams w " +
            "where m.home_team = t.team_id and m.away_team = a.team_id and m.team_won = w.team_id;";
            sta = connection.createStatement();
            // execute the query
            vMatches = sta.executeQuery(vQuerymatches);
            
            java.sql.ResultSetMetaData metaData = vMatches.getMetaData();
            int columnCount = metaData.getColumnCount();
            //String[] columnNames = new String[columnCount];
            String[] scratchNames = new String[columnCount];
            scratchNames[0] = "Match ID";
            scratchNames[1] = "Date Played";
            scratchNames[2] = "Home Team";
            scratchNames[3] = "Away Team";
            scratchNames[4] = "Home Score";
            scratchNames[5] = "Away Score";
            scratchNames[6] = "Winner";
            scratchNames[7] = "Match Abandoned";
            //scratchNames[7] = "plop";
            for (int i = 0; i < columnCount; i++) 
                //columnNames.addElement( metaData.getColumnName(i) );
                columnNames.addElement( scratchNames[i] );
            
            
            //model.setColumnIdentifiers(columnNames);
            
            //Object[] row = new Object[columnCount];
            while (vMatches.next())
            {
                Vector row = new Vector(columnCount);
                for (int i = 1; i <= columnCount; i++)
                {
                    row.addElement(vMatches.getObject(i));
                }
                data.addElement(row);
            }
                    
            JTable table = new JTable(data, columnNames);
            JScrollPane scrollPane = new JScrollPane( table );
            
            JFrame frame = new JFrame("Previous Matches");
            frame.add(scrollPane);

            // Set the size and location of the frame
            frame.setSize(800, 400);
            frame.setLocationRelativeTo(null);

            // Make the frame visible
            frame.setVisible(true);
            
        
            if (columnCount > 0) {
                x = 0;
            }
            
            if (x == 0) {
                // if we get here it broke
                // great JOptionPane.showMessageDialog(NTSubmitDB, "This team already exists");
            } else {
                // it was successfully added to the teams table in the mysql db
                // let the user know
                //JOptionPane.showMessageDialog(NTSubmitDB,
                //            "Welcome, " + msg + "Team has been sucessfully created");
                    }
                    // close the connection to the db and commit
                    connection.close();
                } catch (Exception exception) {
                    exception.printStackTrace();
                }
            
        
    }//GEN-LAST:event_submitbtnActionPerformed

    private void backbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn4ActionPerformed
                // the back button will take us to a new homescreen object
        homescreen hs = new homescreen();
        hs.setVisible(true);
        // close/dispose of the current class
        this.dispose();
    }//GEN-LAST:event_backbtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new previous().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables
}
