/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cricket_Scorer_W10;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author katy
 */
public class teamstatistics extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(teamstatistics.class.getName());

    /**
     * Creates new form teamstatistics
     */
    public teamstatistics() {
        initComponents();
        ResultSet vTeam;
        String url = "jdbc:mysql://185.156.138.148/4-klambert";
        String user = "4-klambert";
        String password = "Duty3-Palace-Area";
        String vQueryTeam = "SELECT team_name FROM Teams";
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
            Connection connect = DriverManager.getConnection(url, user, password);
            PreparedStatement ps2 = connect.prepareStatement(vQueryTeam);
            vTeam = ps2.executeQuery();
            while(vTeam.next()) {
                team.addItem(vTeam.getString("team_name"));
            }
            } catch (Exception e) {
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        team = new javax.swing.JComboBox<>();
        Backbtn3 = new javax.swing.JButton();
        tssubmitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Statistics");

        jLabel2.setText("Choose your team");

        team.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Team" }));

        Backbtn3.setText("Back");
        Backbtn3.addActionListener(this::Backbtn3ActionPerformed);

        tssubmitbutton.setText("Submit");
        tssubmitbutton.addActionListener(this::tssubmitbuttonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(Backbtn3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tssubmitbutton)
                                    .addComponent(team, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Backbtn3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(team, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tssubmitbutton)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Backbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Backbtn3ActionPerformed
        homescreen hs = new homescreen();
        hs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Backbtn3ActionPerformed

    private void tssubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tssubmitbuttonActionPerformed
        // TODO add your handling code here:
        String sTeam = String.valueOf(team.getSelectedItem());
        java.sql.ResultSet vTeamstats = null;
        Statement sta = null;
        String url2 = "jdbc:mysql://185.156.138.148/4-klambert";
        String user2 = "4-klambert";
        String password2 = "Duty3-Palace-Area";
        String vQueryteamstats = null;
        DefaultTableModel model = new DefaultTableModel();
        Vector columnNames = new Vector();
        Vector data = new Vector();  
        int x = 0;
        
        try {
            // create a connection to mysql db 
            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
            Connection connection2 = DriverManager.getConnection(url2, user2, password2);
            // build our sql statement to add a team from the team name box
            // String query = "INSERT INTO Teams (team_name) values('" + Teamname + "')";
            vQueryteamstats = "select m.match_id,m.dateplayed \"Match Date\",t.team_name \"Home Team\",a.team_name \"Away Team\",m.home_score,m.away_score,w.team_name \"Winner\", " +
                "case " +
                "when m.match_abandoned = 0 then 'No' " +
                "else 'Yes' " +
                "end as \"Match Abandoned\" " +
                "from Matches m, Teams t, Teams a, Teams w " +
                "where m.home_team = t.team_id " +
                "and m.away_team = a.team_id " +
                "and m.team_won = w.team_id " +
                "and t.team_name = \""+ sTeam +"\" " +
                "union " +
                "select m.match_id,m.dateplayed \"Match Date\",t.team_name \"Home Team\",a.team_name \"Away Team\",m.home_score,m.away_score,w.team_name \"Winner\", " +
                "case " +
                "when m.match_abandoned = 0 then 'No' " +
                "else 'Yes' " +
                "end as \"Match Abandoned\" " +
                "from Matches m, Teams t, Teams a, Teams w " +
                "where m.home_team = t.team_id " +
                "and m.away_team = a.team_id " +
                "and m.team_won = w.team_id " +
                "and a.team_name = \""+ sTeam +"\";";
            sta = connection2.createStatement();
            // execute the query
            vTeamstats = sta.executeQuery(vQueryteamstats);
            
            java.sql.ResultSetMetaData metaData = vTeamstats.getMetaData();
            int columnCount = metaData.getColumnCount();
            String[] scratchNames = new String[columnCount];
            scratchNames[0] = "Match ID";
            scratchNames[1] = "Date Played";
            scratchNames[2] = "Home Team";
            scratchNames[3] = "Away Team";
            scratchNames[4] = "Home Score";
            scratchNames[5] = "Away Score";
            scratchNames[6] = "Winner";
            scratchNames[7] = "Match Abandoned";
            for (int i = 0; i < columnCount; i++) 
                columnNames.addElement( scratchNames[i] );
            
            
            //model.setColumnIdentifiers(columnNames);
            
            //Object[] row = new Object[columnCount];
            while (vTeamstats.next())
            {
                Vector row = new Vector(columnCount);
                for (int i = 1; i <= columnCount; i++)
                {
                    row.addElement(vTeamstats.getObject(i));
                }
                data.addElement(row);
            }
                    
            JTable table = new JTable(data, columnNames);
            JScrollPane scrollPane = new JScrollPane( table );
            
            JFrame frame = new JFrame("Player Stats");
            frame.add(scrollPane);

            // Set the size and location of the frame
            frame.setSize(800, 400);
            frame.setLocationRelativeTo(null);

            // Make the frame visible
            frame.setVisible(true);
            
        
            if (columnCount > 0) {
                x = 0;
            }
            
            if (x == 0) {
                // if we get here it broke
                // great JOptionPane.showMessageDialog(NTSubmitDB, "This team already exists");
            } else {
                // it was successfully added to the teams table in the mysql db
                // let the user know
                //JOptionPane.showMessageDialog(NTSubmitDB,
                //            "Welcome, " + msg + "Team has been sucessfully created");
                    }
                    // close the connection to the db and commit
                    connection2.close();
                } catch (Exception exception) {
                    exception.printStackTrace();
                }
        
    }//GEN-LAST:event_tssubmitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new teamstatistics().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> team;
    private javax.swing.JButton tssubmitbutton;
    // End of variables declaration//GEN-END:variables
}
